---
- name: download npc-shell
  shell: curl 'https://npc.nos-eastchina1.126.net/dl/install-npc-shell.sh' | /bin/bash
  args:
    creates: /usr/local/bin/npc

- name: npc setup
  shell: npc setup
    --init-ssh-key 
    {% for action in npc_effective_config.actions %}
      --{{ action }}
    {% endfor %}
    {{ dict(
      npc_ssh_key=npc_effective_config.ssh_key,
      npc_instance_type=npc_effective_config.instance_type,
      npc_instance_image=npc_effective_config.instance_image
      ) | to_json | quote }}
    {% if npc_instances is defined %}
      {{ dict(npc_instances=npc_instances ) | to_json | quote }}
    {% endif %}
    {% if npc_effective_config.log is defined %}
      2>> {{ npc_effective_config.log | quote }}
    {% endif %}
  args:
    executable: /bin/bash
  vars:
    npc_effective_config: "{{ npc_default_config | combine(npc_config|default({})) }}"
  environment:
    NPC_API_ENDPOINT: "{{ npc_effective_config.api_endpoint | default('') }}"
    NPC_API_KEY: "{{ npc_effective_config.app_key | default('') }}"
    NPC_API_SECRET: "{{ npc_effective_config.app_secret | default('') }}"
    NPC_ACTION_FORKS: "{{ npc_effective_config.action_focks | default('') }}"
    NPC_ACTION_TIMEOUT: "{{ npc_effective_config.action_timeout | default('') }}"
    NPC_ACTION_PULL_SECONDS: "{{ npc_effective_config.action_pull_interval | default('') }}"
    NPC_ACTION_RETRY_SECONDS: "{{ npc_effective_config.action_retry_interval | default('') }}"
  register: npc_execution
  changed_when: false

- name: register 'npc' fact
  set_fact:
    npc: "{{ npc_execution.stdout | from_json }}"

- name: refresh inventory
  meta: refresh_inventory
  when: npc.instances is defined

- name: add hosts
  with_items: "{{ npc.instances | default([]) }}"
  add_host:
    hostname: "{{ item.name }}"
    ansible_host: "{{ item.lan_ip }}"
    ansible_ssh_private_key_file: "{{ item.ssh_key_file }}"
    groups: "{{ item.groups }}"
    npc_instance: "{{ item }}"
  changed_when: false

- name: summary instances
  when: npc.instances is defined
  debug: 
    msg: "{{npc.instances|length}} instances registered: {{npc.instances|map(attribute='name')|join(', ')}}"
  changed_when: npc.changed
