---
- name: prepare
  block:
    - shell: curl 'https://npc.nos-eastchina1.126.net/dl/install-npc-shell.sh' | /bin/bash
      args:
        creates: /usr/bin/npc
    - copy: src={{item}} dest=/usr/npc-shell/
      with_fileglob:
        - npc-setup.*.sh
    - copy: src={{item}} dest=/usr/npc-shell/ mode=0755
      with_fileglob:
        - npc-setup.sh
        - npc-playbook.sh
    - vars:
        npc_default_config:
          app_key: 
          app_secret:
          default_instance_image: 
          default_instance_type:
            cpu: 2
            memory: 4G   
      set_fact:
        npc_effective_config: "{{ npc_effective_config | default(npc_default_config) | combine(npc_config|default({})) }}"
        npc_resources: "{{ dict(
            npc_instance_images=npc_instance_images|default(false),
            npc_volumes=npc_volumes|default(false),
            npc_instances=npc_instances|default(false)
          ) }}"

- name: setup
  block:
    - include: npc_setup.yml
      vars:
        npc_actions: '{{ (npc_setup | default({})).staging | default(false) | ternary(["init","suspend"], (npc_setup | default({})).actions | default([])) }}'

    - name: notify to resume npc_setup
      when: (npc_setup | default({})).staging | default(false)
      debug: msg='npc.changing={{npc.changing}}'
      notify: resume npc_setup
      changed_when: true
