---
- name: npc setup
  shell: npc setup
    {% if (npc_setup | default({})).init_ssh_key | default(npc_effective_config.ssh_key|default(false,true) != false) %}
      --init-ssh-key 
    {% endif %}
    {% if (npc_setup | default({})).absent | default("omit") != "destroy" %}
      --omit-absent 
      {% if (npc_setup | default({})).filter_by_ssh_key | default(false) %}
        --filter-by-ssh-key
      {% endif %}
    {% elif (npc_setup | default({})).filter_by_ssh_key | default(true) %}
      --filter-by-ssh-key
    {% endif %}
    {% for action in npc_actions %}
      --{{ action }}
    {% endfor %}
    {{ dict(
      npc_ssh_key=npc_effective_config.ssh_key|default(false),
      npc_instance_type=npc_effective_config.default_instance_type,
      npc_instance_image=npc_effective_config.default_instance_image
      ) | to_json | quote }}
    {{ npc_resources | to_json | quote }}
    {% if ((npc_setup | default({})).log | default("")) | length > 0 %}
      2>> {{ (npc_setup | default({})).log | quote }}
    {% endif %}
  args:
    executable: /bin/bash
  environment:
    NPC_API_ENDPOINT: "{{ npc_effective_config.api_endpoint | default('') }}"
    NPC_API_KEY: "{{ npc_effective_config.app_key | default('') }}"
    NPC_API_SECRET: "{{ npc_effective_config.app_secret | default('') }}"
    NPC_ACTION_FORKS: "{{ (npc_setup | default({})).action_focks | default('') }}"
    NPC_ACTION_TIMEOUT: "{{ (npc_setup | default({})).action_timeout | default('') }}"
    NPC_ACTION_PULL_SECONDS: "{{ (npc_setup | default({})).action_pull_interval | default('') }}"
    NPC_ACTION_RETRY_SECONDS: "{{ (npc_setup | default({})).action_retry_interval | default('') }}"
  register: npc_execution
  changed_when: false

- name: export 'npc'
  set_fact:
    npc: "{{ npc_execution.stdout | from_json }}"

- name: summary
  debug: 
    msg: npc_setup - 
      {% if npc.changing %}
      {{npc.creating|default([])|length}} creating, 
      {{npc.updating|default([])|length}} updating, 
      {{npc.destroying|default([])|length}} destroying,
      {% else %}
        0 changing,
      {% endif %}
      {% if npc.changed %}
      {{npc.created|default([])|length}} created, 
      {{npc.updated|default([])|length}} updated, 
      {{npc.destroyed|default([])|length}} destroyed.
      {% else %}
        0 changed.
      {% endif %}
  changed_when: npc.changed

- name: register hosts
  when:
    - npc.instances is defined
    - (npc_setup | default({})).add_hosts | default(true)
  block:
    - name: add hosts
      with_items: "{{ npc.instances.values() }}"
      vars:
          npc_group_by: '{{ ((npc_setup | default({})).group_by | default({}, true)) }}'
          npc_change_group: '{{npc_group_by[item.change_action|default("none", true)]|default("", true)}}'
          npc_all_group: '{{npc_group_by["all"]|default("", true)}}'
          npc_groups: '{{ ((npc_all_group | length > 0) | ternary([npc_all_group],[])) + ((npc_change_group | length > 0) | ternary([npc_change_group],[])) }}'
          ssh_host_by: '{{item.ssh_host_by|default(npc_effective_config.ssh_host_by|default("lan_ip"))}}'
          ssh_jump_host: '{{item.ssh_jump_host|default(npc_effective_config.ssh_jump_host)|default(false,true)}}'
          ssh_jump_user: '{{item.ssh_jump_user|default(npc_effective_config.ssh_jump_user)|default(false,true)}}'
          ssh_jump_key_file: '{{item.ssh_jump_key_file|default(npc_effective_config.ssh_jump_key_file)|default(false,true)}}'
          npc_jump_vars: '{{npc.instances[ssh_jump_host]|default({})}}'
          ssh_jump_vars: '{{hostvars[ssh_jump_host]|default({})}}'
          ssh_jump_args: '{% if ssh_jump_host != false %}-o ProxyCommand="ssh -W %h:%p -q 
            {% if npc.instances.has_key(ssh_jump_host) %}
              {% if ssh_jump_key_file|default(npc_jump_vars.ssh_key_file,true)|default(false) %}
                -i {{ ssh_jump_key_file|default(npc_jump_vars.ssh_key_file,true) }}
              {% endif %}
              {% if ssh_jump_user|default(npc_jump_vars.ssh_user,true)|default(false) %}{{ssh_jump_user|default(npc_jump_vars.ssh_user,true)}}@{% endif %}{{npc_jump_vars[npc_jump_vars.ssh_host_by|default(npc_effective_config.ssh_host_by|default("lan_ip"))]}}
            {% else %}
              {% if ssh_jump_key_file|default(ssh_jump_vars.ansible_ssh_private_key_file,true)|default(false) %}
                -i {{ ssh_jump_key_file|default(ssh_jump_vars.ansible_ssh_private_key_file,true) }}
              {% endif %}
              {% if ssh_jump_user|default(ssh_jump_vars.ansible_user,true)|default(false) %}{{ssh_jump_user|default(ssh_jump_vars.ansible_user,true)}}@{% endif %}{{ssh_jump_vars.ansible_host|default(ssh_jump_host)}}
            {% endif %}"{% endif %}'
      add_host: 
      args: '{{ dict(
          hostname=item.name,
          groups=( (npc_effective_config.groups|default([])) + (item.groups | default([])) + npc_groups ),
          ansible_host=item[ssh_host_by],
          ansible_user=(item.ssh_user|default(omit)),
          ansible_ssh_common_args=((ssh_jump_host != false)|ternary(ssh_jump_args, omit) ),
          ansible_ssh_private_key_file=(item.ssh_key_file|default(omit)),
          npc_instance=item
          ) | combine( npc_effective_config.vars|default({},true), item.vars|default({},true) ) }}'
      changed_when: false
    - name: summary
      debug: 
        msg: "{{npc.instances|length}} instances registered: {{npc.instances.keys()|join(', ')}}"
